### ISSUE TITLE
clarification on the flashinfer performance (using Tensor Cores or CUDA Cores for row-sum)

### ISSUE THREAD

**Issue by yzh119** [luliyucoordinate/cute-flash-attention#1]
Hi @luliyucoordinate , thanks for the great work.

FlashInfer converted the row-sum implementation from CUDA cores to Tensor Cores in a commit a year ago (https://github.com/flashinfer-ai/flashinfer/commit/e0ffc4b21b5a963c4ad831fb1a2263c285e38e8b#diff-803bb3474c714c44553994f8d34d411777293dae8a5c091716079a4b4b202f6bR529-R554), the basic idea is that sum reduction of $P$ matrix can be converted to $P\cdot \mathcal{1}$ where $\mathcal{1}$ is an all-ones matrix (this paper has a more defailed explanation: https://arxiv.org/pdf/1811.09736), and in practice we issue a m16n8k16 mma instruction (https://github.com/flashinfer-ai/flashinfer/blob/398cd2b940a1460efde471a7428d2d5faae07508/include/flashinfer/mma.cuh#L518-L579), we actually only need a `m16n1k16` but the minimal `n` size in mma instruction is 8, so we wasted 7/8 of the tensor cores flops with this instruction.

For GPUs such as A100/H100, the FLOPs ratio between CUDA Cores and Tensor Cores is around 1:16, thus such optimizations can be useful because even if we wasted 7/8 of the computation, Tensor Cores flops is still higher. But it's not the case for GPUs such as 30*, 40*, A6000, Ada6000 or L40s where CUDA Cores and Tensor Cores TFLOPs/s ratio is 1:2, and using Tensor Cores for reduction doesn't make sense here and can harm performance. I'm considering adding back an option of using CUDA Cores for row-sum reduction in FlashInfer later.

Just create this issue to discuss this specific item (row-sum implementation) because I feel it could an interesting topic to you as well, feel free to close it anytime :)

**Comment by luliyucoordinate** [comment]
I understand the optimization of Tensor Cores you mentioned; it's a really great idea.
